import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import { FullPortalData, PaymentItem, PortalSettings, TermSection, PortalConfig, TableColumn } from './types';

const DATA_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'db.json');

export const DEFAULT_TABLE_COLUMNS: TableColumn[] = [
  { id: 'col-sno', key: 'sNo', label: 'S. No.', visible: true },
  { id: 'col-formNumber', key: 'formNumber', label: 'Form Number', visible: true },
  { id: 'col-applicationNumber', key: 'applicationNumber', label: 'Application Number', visible: true },
  { id: 'col-referenceNumber', key: 'referenceNumber', label: 'App. Ref. No.', visible: true },
  { id: 'col-classes', key: 'classes', label: 'Classes', visible: true },
  { id: 'col-branch', key: 'branch', label: 'Branch', visible: true },
  { id: 'col-price', key: 'price', label: 'Price', visible: true }
];

// Default initial Emblem Logo as clean inline SVG Data URL
const DEFAULT_LOGO = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="80" height="80"><circle cx="50" cy="50" r="45" fill="%2300485F" /><path d="M50 15 L58 35 L80 35 L62 48 L68 70 L50 56 L32 70 L38 48 L20 35 L42 35 Z" fill="%23FFD700" /><text x="50" y="85" font-family="Arial" font-size="10" font-weight="bold" fill="%23FFFFFF" text-anchor="middle">IP INDIA</text></svg>`;

const INITIAL_DATA: FullPortalData = {
  portalSettings: {
    logo: "/images/ip-india-logo.svg",
    emblemImage: "/images/ashoka-emblem.svg",
    organizationName: "Office of the Controller General of Patents, Designs & Trade Marks",
    departmentName: "Department of Industrial Policy & Promotion,",
    attorneyName: "RAJESH & ASSOCIATES",
    attorneyNumber: "ATT/2024/7741"
  },
  payments: [
    {
      id: "pay-1",
      sNo: 1,
      formNumber: "TM-A",
      applicationNumber: "5948301",
      referenceNumber: "TM/2024/88921",
      classes: "35, 42",
      branch: "MUMBAI",
      price: 4500
    },
    {
      id: "pay-2",
      sNo: 2,
      formNumber: "TM-M",
      applicationNumber: "5948302",
      referenceNumber: "TM/2024/88922",
      classes: "35",
      branch: "DELHI",
      price: 900
    }
  ],
  tableColumns: DEFAULT_TABLE_COLUMNS,
  terms: [
    {
      id: "term-1",
      order: 1,
      title: "1. Payment Gateway/ Net Banking Disclaimer",
      description: "All the payments made by the user of the IPO online services may be made using the NTRP Payment Gateway hosted by Department of Expenditure, Ministry of Finance. The Payment Gateway/ Internet Banking service is provided to you in order to facilitate the filing procedures using the online services provided by the IPO. By using the services, of the payment gateway, you expressly agree that your use of this online payment service is entirely at your own risk."
    },
    {
      id: "term-2",
      order: 2,
      title: "2. Transaction charge",
      description: "The necessary transaction charge plus service tax as applicable for online payment of the services will be borne by the user. The list of charges for using various payment gateway services is available on the NTRP Portal at website i.e. https://bharatkosh.gov.in/"
    },
    {
      id: "term-3",
      order: 3,
      title: "3. Transaction Process /Refund Policy:",
      description: `Please refer to Terms and Conditions available on the NTRP Portal at website i.e. https://bharatkosh.gov.in/

The procedure adopted by IPO for online payment is as follows:

1. An applicant prepares a draft of completed form/set of forms and goes for payment where a unique transaction number is generated by the IPO portal and is forwarded to payment gateway along with requisite amount of fee.

2. At the payment gateway, the user is asked to choose a payment option and the bank for making the payment.

3. For all the transactions where success status is received from the payment gateway, an acknowledgement gets generated at the IPO portal.

4. For transactions that are unsuccessful (Failed) at payment gateway, if the amount is debited from the user’s bank account and payment gateway shows unsuccessful (Failed) transaction then in such cases, the amount will be refunded by the payment gateway to the users as per terms and conditions of NTRP Portal available at https://bharatkosh.gov.in/

5. In case where the transaction has been unsuccessful (Failed), the users are advised to wait for at least 60 minutes before re-attempting the transactions. Users are also advised to ensure that the payment gateway shows the status as " Transaction Failed" against the previous attempt, to avoid multiple payments against the same set of applications.

6. In case the "acknowledgement" is not generated against a "successful" transaction and the payment gateway shows "Success", then there is no need to make another payment for the same set of applications. In case a user makes second or any further payment with respect to "successful" transaction of same form/set of forms, no amount would be refunded by IPO.`
    },
    {
      id: "term-4",
      order: 4,
      title: "4. Receipt generation",
      description: "In case of successful transactions, a receipt containing, the details of forms submitted shall be generated."
    },
    {
      id: "term-5",
      order: 5,
      title: "5. Limitation of Liability",
      description: `IPO expressly disclaims any claim or liability arising out of the provision of this service. By using this service, the user expressly agree and acknowledge that he/she shall be solely responsible for his/her conduct and that IPO reserves the right to terminate the rights of user to use the service immediately. IPO shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, data or other intangible losses arising out of or in connection with use of the Payment Gateway.

IPO assumes no liability whatsoever for any monetary or other damage suffered by

the user on account of:

(i) The delay, failure or interruption of portal / payment gateway services or corruption of any data or other information transmitted in connection with use of the Payment Gateway/ Internet Banking;

(ii) By using these services, the user agrees, understand and confirm that personal data including without limitation details relating to debit card/credit card/ Net Banking transmitted over the internet is susceptible to misuse, theft and/or fraud and that IPO has no control over such matters. Although all reasonable care has been taken towards guarding against unauthorized use of any information transmitted by you, IPO does not represent or guarantee that the use of the payment gateway/ Internet Banking will not result in theft and/or unauthorized use of data over the internet.`
    },
    {
      id: "term-6",
      order: 6,
      title: "6. Debit/Credit card / Net banking details",
      description: "The user shall not use a debit/credit card/ Net Banking which is not lawfully owned by him/her. In default of the above conditions IPO shall be entitled to recover the amount of transaction from the user against whom the credit / debit card/ Net banking has been used. Further, IPO also reserves the right to initiate any legal action for recovery of cost / penalty or any other punitive measure, as it may deem fit."
    }
  ],
  settings: {
    redirectURL: "https://ipindiaonline.gov.in/trademarkefiling/user/frmLoginNew.aspx"
  },
  admin: {
    username: "admin",
    passwordHash: bcrypt.hashSync("admin123", 10)
  }
};

declare global {
  var __PORTAL_DB__: FullPortalData | undefined;
}

const TMP_DB_FILE = path.join('/tmp', 'db.json');

export function getDbData(): FullPortalData {
  if (globalThis.__PORTAL_DB__) {
    return globalThis.__PORTAL_DB__;
  }

  try {
    // 1. Try reading from /tmp/db.json first (serverless writable disk)
    if (fs.existsSync(TMP_DB_FILE)) {
      const raw = fs.readFileSync(TMP_DB_FILE, 'utf-8');
      const parsed = JSON.parse(raw) as FullPortalData;
      if (parsed && Array.isArray(parsed.payments)) {
        if (!parsed.tableColumns || !Array.isArray(parsed.tableColumns) || parsed.tableColumns.length === 0) {
          parsed.tableColumns = DEFAULT_TABLE_COLUMNS;
        }
        globalThis.__PORTAL_DB__ = parsed;
        return parsed;
      }
    }

    // 2. Try reading from project data/db.json
    if (fs.existsSync(DB_FILE)) {
      const raw = fs.readFileSync(DB_FILE, 'utf-8');
      const parsed = JSON.parse(raw) as FullPortalData;
      if (!parsed.tableColumns || !Array.isArray(parsed.tableColumns) || parsed.tableColumns.length === 0) {
        parsed.tableColumns = DEFAULT_TABLE_COLUMNS;
      }
      globalThis.__PORTAL_DB__ = parsed;
      return parsed;
    }
  } catch (error) {
    console.error('Error reading DB data:', error);
  }

  globalThis.__PORTAL_DB__ = INITIAL_DATA;
  return INITIAL_DATA;
}

export function saveDbData(data: FullPortalData): void {
  // Always update in-memory cache instantly so GET /api/v1/public-data immediately returns updated data
  globalThis.__PORTAL_DB__ = data;

  // 1. Write to /tmp/db.json (always writable in Vercel Serverless Functions)
  try {
    fs.writeFileSync(TMP_DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
  } catch (err) {
    console.error('Error writing to /tmp/db.json:', err);
  }

  // 2. Write to project data/db.json (writable in local development)
  try {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf-8');
  } catch (err) {
    // Ignore EROFS error on Vercel production serverless filesystem
  }
}
